"""Account feature engineering public API."""

from graph_aml.features.account import (
    ACCOUNT_FEATURE_COLUMNS,
    EXTENDED_ACCOUNT_FEATURE_COLUMNS,
    AccountFeatureConfig,
    build_account_universe,
    calculate_account_features,
    calculate_extended_account_features,
    calculate_extended_features_for_date,
    calculate_features_for_date,
    prepare_transactions_for_features,
    validate_account_features,
    validate_extended_account_features,
)
from graph_aml.features.artefacts import (
    generate_account_feature_artefacts,
    generate_extended_account_feature_artefacts,
    write_account_feature_summary_json,
    write_account_features_csv,
)
from graph_aml.features.audit import write_feature_persistence_audit_event
from graph_aml.features.behavioural import (
    BEHAVIOURAL_FEATURE_COLUMNS,
    calculate_behavioural_features_for_date,
    calculate_below_threshold_count_24h,
    calculate_counterparty_entropy,
    calculate_dormant_days_before_activity,
    calculate_retained_balance_proxy,
)
from graph_aml.features.exceptions import (
    AccountFeatureError,
    FeatureArtefactError,
    FeatureAuditError,
    FeatureEngineeringError,
    FeatureInputError,
    FeaturePersistenceError,
    MartFeatureReadError,
    StagedFeatureReadError,
)
from graph_aml.features.jurisdiction import (
    JURISDICTION_FEATURE_COLUMNS,
    calculate_cross_border_ratio_30d,
    calculate_high_risk_country_exposure,
    calculate_jurisdiction_features_for_date,
)
from graph_aml.features.mart import (
    get_mart_account_feature_date_range,
    get_mart_account_feature_versions,
    read_mart_account_features,
)
from graph_aml.features.persistence import (
    MART_ACCOUNT_FEATURE_COLUMNS,
    MART_ACCOUNT_FEATURE_TABLE,
    calculate_and_persist_account_features_from_staged,
    persist_account_features,
    prepare_account_features_for_persistence,
    upsert_account_features,
)
from graph_aml.features.staged import (
    calculate_account_features_from_staged,
    calculate_extended_account_features_from_staged,
    read_staged_accounts_for_features,
    read_staged_countries_for_features,
    read_staged_extended_feature_inputs,
    read_staged_feature_inputs,
    read_staged_transactions_for_features,
)
from graph_aml.features.summary import summarise_account_features
from graph_aml.features.windows import (
    build_feature_date_range,
    filter_transactions_for_window,
    normalise_feature_date,
)

__all__ = [
    "ACCOUNT_FEATURE_COLUMNS",
    "AccountFeatureConfig",
    "AccountFeatureError",
    "BEHAVIOURAL_FEATURE_COLUMNS",
    "EXTENDED_ACCOUNT_FEATURE_COLUMNS",
    "FeatureAuditError",
    "FeatureArtefactError",
    "FeatureEngineeringError",
    "FeatureInputError",
    "FeaturePersistenceError",
    "JURISDICTION_FEATURE_COLUMNS",
    "MART_ACCOUNT_FEATURE_COLUMNS",
    "MART_ACCOUNT_FEATURE_TABLE",
    "MartFeatureReadError",
    "StagedFeatureReadError",
    "build_account_universe",
    "build_feature_date_range",
    "calculate_and_persist_account_features_from_staged",
    "calculate_behavioural_features_for_date",
    "calculate_below_threshold_count_24h",
    "calculate_counterparty_entropy",
    "calculate_cross_border_ratio_30d",
    "calculate_dormant_days_before_activity",
    "calculate_extended_account_features",
    "calculate_extended_account_features_from_staged",
    "calculate_extended_features_for_date",
    "calculate_high_risk_country_exposure",
    "calculate_jurisdiction_features_for_date",
    "calculate_retained_balance_proxy",
    "calculate_account_features",
    "calculate_account_features_from_staged",
    "calculate_features_for_date",
    "filter_transactions_for_window",
    "generate_account_feature_artefacts",
    "generate_extended_account_feature_artefacts",
    "get_mart_account_feature_date_range",
    "get_mart_account_feature_versions",
    "normalise_feature_date",
    "persist_account_features",
    "prepare_transactions_for_features",
    "prepare_account_features_for_persistence",
    "read_mart_account_features",
    "read_staged_accounts_for_features",
    "read_staged_countries_for_features",
    "read_staged_extended_feature_inputs",
    "read_staged_feature_inputs",
    "read_staged_transactions_for_features",
    "summarise_account_features",
    "upsert_account_features",
    "validate_account_features",
    "validate_extended_account_features",
    "write_feature_persistence_audit_event",
    "write_account_feature_summary_json",
    "write_account_features_csv",
]
