"""Composite account risk scoring utilities."""

from graph_aml.scoring.artefacts import (
    generate_account_risk_score_artefacts,
    write_account_risk_score_persistence_summary_json,
    write_account_risk_score_summary_json,
    write_account_risk_scores_csv,
    write_account_risk_scores_json,
)
from graph_aml.scoring.components import (
    RISK_COMPONENT_COLUMNS,
    build_account_risk_components,
    clip_score,
    compute_anomaly_risk_component,
    compute_customer_risk_component,
    compute_graph_risk_component,
    compute_jurisdiction_risk_component,
    compute_rule_risk_component,
    map_risk_rating_to_score,
    map_severity_to_score,
    percentile_rank_score,
)
from graph_aml.scoring.composite import (
    ACCOUNT_RISK_SCORE_COLUMNS,
    AccountRiskScoreResult,
    assign_account_risk_band,
    compute_account_risk_scores,
    compute_account_risk_scores_from_inputs,
    compute_and_persist_account_risk_scores,
)
from graph_aml.scoring.config import (
    AccountRiskScoringConfig,
    account_risk_scoring_config_from_mapping,
    load_account_risk_scoring_config,
    validate_account_risk_scoring_config,
)
from graph_aml.scoring.exceptions import (
    ScoringComputationError,
    ScoringConfigurationError,
    ScoringError,
    ScoringInputError,
    ScoringPersistenceError,
    ScoringValidationError,
)
from graph_aml.scoring.inputs import (
    read_scoring_accounts,
    read_scoring_alerts,
    read_scoring_anomaly_scores,
    read_scoring_feature_inputs,
    read_scoring_graph_features,
)
from graph_aml.scoring.persistence import (
    AccountRiskScorePersistenceConfig,
    AccountRiskScorePersistenceResult,
    build_account_risk_score_upsert_sql,
    persist_account_risk_scores,
    prepare_account_risk_scores_for_persistence,
    upsert_account_risk_scores,
    validate_account_risk_score_persistence_config,
    write_account_risk_score_audit_event,
)
from graph_aml.scoring.readers import (
    read_account_risk_score_summary,
    read_account_risk_score_versions,
    read_account_risk_scores,
    read_latest_account_risk_scores,
)
from graph_aml.scoring.summary import (
    account_risk_score_result_to_dict,
    summarise_account_risk_scores,
    summarise_risk_components,
)
from graph_aml.scoring.validation import (
    build_account_risk_score_quality_summary,
    compare_account_risk_score_row_counts,
    validate_account_risk_score_frame,
    validate_prepared_account_risk_score_frame,
    validate_risk_component_frame,
)

__all__ = [
    "ACCOUNT_RISK_SCORE_COLUMNS",
    "RISK_COMPONENT_COLUMNS",
    "AccountRiskScorePersistenceConfig",
    "AccountRiskScorePersistenceResult",
    "AccountRiskScoreResult",
    "AccountRiskScoringConfig",
    "ScoringComputationError",
    "ScoringConfigurationError",
    "ScoringError",
    "ScoringInputError",
    "ScoringPersistenceError",
    "ScoringValidationError",
    "account_risk_score_result_to_dict",
    "account_risk_scoring_config_from_mapping",
    "assign_account_risk_band",
    "build_account_risk_components",
    "build_account_risk_score_quality_summary",
    "build_account_risk_score_upsert_sql",
    "clip_score",
    "compare_account_risk_score_row_counts",
    "compute_account_risk_scores",
    "compute_account_risk_scores_from_inputs",
    "compute_and_persist_account_risk_scores",
    "compute_anomaly_risk_component",
    "compute_customer_risk_component",
    "compute_graph_risk_component",
    "compute_jurisdiction_risk_component",
    "compute_rule_risk_component",
    "generate_account_risk_score_artefacts",
    "load_account_risk_scoring_config",
    "map_risk_rating_to_score",
    "map_severity_to_score",
    "percentile_rank_score",
    "persist_account_risk_scores",
    "prepare_account_risk_scores_for_persistence",
    "read_account_risk_score_summary",
    "read_account_risk_score_versions",
    "read_account_risk_scores",
    "read_latest_account_risk_scores",
    "read_scoring_accounts",
    "read_scoring_alerts",
    "read_scoring_anomaly_scores",
    "read_scoring_feature_inputs",
    "read_scoring_graph_features",
    "summarise_account_risk_scores",
    "summarise_risk_components",
    "upsert_account_risk_scores",
    "validate_account_risk_score_frame",
    "validate_account_risk_score_persistence_config",
    "validate_account_risk_scoring_config",
    "validate_prepared_account_risk_score_frame",
    "validate_risk_component_frame",
    "write_account_risk_score_audit_event",
    "write_account_risk_score_persistence_summary_json",
    "write_account_risk_score_summary_json",
    "write_account_risk_scores_csv",
    "write_account_risk_scores_json",
]
