"""Analyst feedback labels and supervised-readiness datasets."""

from __future__ import annotations

from graph_aml.labels.artefacts import (
    generate_label_artefacts,
    write_account_labels_csv,
    write_account_supervised_dataset_csv,
    write_case_labels_csv,
    write_case_supervised_dataset_csv,
    write_label_quality_summary_json,
)
from graph_aml.labels.config import (
    AnalystLabelConfig,
    LabelLeakageControlConfig,
    LabelPropagationConfig,
    LabelQualityConfig,
    analyst_label_config_from_mapping,
    load_analyst_label_config,
    validate_analyst_label_config,
)
from graph_aml.labels.dataset import (
    ACCOUNT_SUPERVISED_DATASET_COLUMNS,
    CASE_SUPERVISED_DATASET_COLUMNS,
    LabelDatasetBuildResult,
    build_account_supervised_dataset,
    build_and_persist_label_datasets,
    build_case_supervised_dataset,
    build_label_datasets_from_inputs,
)
from graph_aml.labels.exceptions import (
    LabelConfigurationError,
    LabelDatasetError,
    LabelError,
    LabelInputError,
    LabelMappingError,
    LabelPersistenceError,
    LabelValidationError,
)
from graph_aml.labels.inputs import (
    read_label_account_features,
    read_label_account_risk_scores,
    read_label_anomaly_scores,
    read_label_case_entities,
    read_label_case_risk_scores,
    read_label_cases,
    read_label_graph_features,
    read_label_inputs,
    read_label_lifecycle_events,
)
from graph_aml.labels.mapping import (
    ACCOUNT_LABEL_COLUMNS,
    CASE_LABEL_COLUMNS,
    build_account_labels,
    build_case_labels,
    label_name_from_binary_value,
    map_status_to_binary_label,
    normalise_label_status,
    select_latest_eligible_decision_events,
)
from graph_aml.labels.persistence import (
    LabelPersistenceConfig,
    LabelPersistenceResult,
    build_account_label_upsert_sql,
    build_account_supervised_dataset_upsert_sql,
    build_case_label_upsert_sql,
    build_case_supervised_dataset_upsert_sql,
    persist_label_datasets,
    prepare_label_frames_for_persistence,
    upsert_label_frame,
    validate_label_persistence_config,
    write_label_generation_audit_event,
)
from graph_aml.labels.readers import (
    read_account_labels,
    read_account_supervised_dataset,
    read_case_labels,
    read_case_supervised_dataset,
    read_label_summary,
)
from graph_aml.labels.summary import (
    label_dataset_result_to_dict,
    summarise_account_labels,
    summarise_case_labels,
    summarise_supervised_dataset,
)
from graph_aml.labels.validation import (
    build_label_quality_summary,
    compare_label_row_counts,
    validate_account_labels,
    validate_case_labels,
    validate_label_dataset_result,
)

__all__ = [
    "ACCOUNT_LABEL_COLUMNS",
    "ACCOUNT_SUPERVISED_DATASET_COLUMNS",
    "AnalystLabelConfig",
    "CASE_LABEL_COLUMNS",
    "CASE_SUPERVISED_DATASET_COLUMNS",
    "LabelConfigurationError",
    "LabelDatasetBuildResult",
    "LabelDatasetError",
    "LabelError",
    "LabelInputError",
    "LabelLeakageControlConfig",
    "LabelMappingError",
    "LabelPersistenceConfig",
    "LabelPersistenceError",
    "LabelPersistenceResult",
    "LabelPropagationConfig",
    "LabelQualityConfig",
    "LabelValidationError",
    "analyst_label_config_from_mapping",
    "build_account_label_upsert_sql",
    "build_account_labels",
    "build_account_supervised_dataset",
    "build_account_supervised_dataset_upsert_sql",
    "build_and_persist_label_datasets",
    "build_case_label_upsert_sql",
    "build_case_labels",
    "build_case_supervised_dataset",
    "build_case_supervised_dataset_upsert_sql",
    "build_label_datasets_from_inputs",
    "build_label_quality_summary",
    "compare_label_row_counts",
    "generate_label_artefacts",
    "label_dataset_result_to_dict",
    "label_name_from_binary_value",
    "load_analyst_label_config",
    "map_status_to_binary_label",
    "normalise_label_status",
    "persist_label_datasets",
    "prepare_label_frames_for_persistence",
    "read_account_labels",
    "read_account_supervised_dataset",
    "read_case_labels",
    "read_case_supervised_dataset",
    "read_label_account_features",
    "read_label_account_risk_scores",
    "read_label_anomaly_scores",
    "read_label_case_entities",
    "read_label_case_risk_scores",
    "read_label_cases",
    "read_label_graph_features",
    "read_label_inputs",
    "read_label_lifecycle_events",
    "read_label_summary",
    "select_latest_eligible_decision_events",
    "summarise_account_labels",
    "summarise_case_labels",
    "summarise_supervised_dataset",
    "upsert_label_frame",
    "validate_account_labels",
    "validate_analyst_label_config",
    "validate_case_labels",
    "validate_label_dataset_result",
    "validate_label_persistence_config",
    "write_account_labels_csv",
    "write_account_supervised_dataset_csv",
    "write_case_labels_csv",
    "write_case_supervised_dataset_csv",
    "write_label_generation_audit_event",
    "write_label_quality_summary_json",
]
